[package]
name = "rusix-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rusix-ir.workspace = true
rusix-nix.workspace = true
serde_json.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile.workspace = true
