use crate::ast::{BinaryOp, Builtin, NixExpr, NixKind};
use rusnix_ir::Origin;
use serde::{Deserialize, Serialize};

/// A range of generated Nix text linked to the Rust operation that created it.
/// `start` is inclusive and `end` exclusive. Nested ranges let a Nix error
/// position identify the most specific Rust expression and its surrounding
/// configuration path.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SourceSpan {
    /// Inclusive UTF-8 byte offset from the start of [`Generated::source`].
    pub start: usize,
    /// Exclusive byte offset; the byte at `end` belongs outside this span.
    pub end: usize,
    /// Rust origin of the expression occupying this range.
    pub origin: Origin,
    /// Enclosing Rust operations, such as the containing field assignment.
    /// These explain the configuration path even without runtime error markers.
    #[serde(default)]
    pub enclosing: Vec<Origin>,
    /// Whether this range identifies an operation’s own failure without a runtime marker.
    /// Used when choosing between a generated failure position and an enclosing call;
    /// literal values and function definitions cannot displace the consuming operation.
    #[serde(default)]
    pub diagnostic_site: bool,
}

/// Nix source produced by the compiler, with its links back to Rust locations.
/// Save the source and spans together to translate later Nix error positions.
/// This is output to inspect or evaluate; normal configuration authors edit
/// Rust rather than this generated text.
#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Generated {
    /// Complete rendered expression, including selected runtime error contexts.
    /// Fine-grained origin comments are present only when explicitly requested.
    pub source: String,
    /// Text ranges linked to Rust operations and their enclosing configuration fields.
    pub spans: Vec<SourceSpan>,
}

/// Control optional aids for manually inspecting generated Nix.
/// Source maps and runtime diagnostic boundaries are preserved regardless of
/// these options. Each rendering produces spans for its own source text.
#[derive(Clone, Copy, Debug, Default)]
pub struct RenderOptions {
    /// Show `# rn-...` before each attributed expression for human inspection.
    /// Defaults to false. Diagnostics use source maps and selected runtime
    /// contexts, not these comments.
    pub origin_comments: bool,
}

impl Generated {
    /// Find the first source-map origin with this ID; reused expressions may have several spans.
    pub fn origin(&self, id: &str) -> Option<&Origin> {
        self.spans
            .iter()
            .find(|span| span.origin.id == id)
            .map(|span| &span.origin)
    }

    /// Find the narrowest origin at a one-based generated line and byte column.
    /// Returns `None` for invalid positions or compiler syntax with no attribution.
    pub fn at_position(&self, line: usize, column: usize) -> Option<&Origin> {
        self.span_at_position(line, column).map(|span| &span.origin)
    }

    /// Find the narrowest half-open span containing a one-based line and byte column.
    /// This preserves ancestry when runtime error contexts have disappeared.
    pub fn span_at_position(&self, line: usize, column: usize) -> Option<&SourceSpan> {
        if line == 0 || column == 0 {
            return None;
        }

        let start = if line == 1 {
            0
        } else {
            self.source.match_indices('\n').nth(line - 2)?.0 + 1
        };
        let line_end = self.source[start..]
            .find('\n')
            .map_or(self.source.len(), |n| start + n);
        let offset = start.checked_add(column - 1)?;
        if offset >= line_end {
            return None;
        }

        self.spans
            .iter()
            .filter(|span| span.start <= offset && offset < span.end)
            .min_by_key(|span| span.end - span.start)
    }
}

/// Render advanced backend syntax into escaped Nix source and attribution ranges.
/// Does not validate or evaluate the AST; ordinary callers should use [`crate::compile`]
/// or [`crate::nixos::compile_module`] to validate semantic IR first.
pub fn render(ast: &NixExpr) -> Generated {
    render_with_options(ast, RenderOptions::default())
}

/// Render Nix with optional origin comments for manual inspection.
/// This uses the same renderer and runtime contexts as [`render`]; spans are
/// recomputed for this output rather than reused from another rendering.
pub fn render_with_options(ast: &NixExpr, options: RenderOptions) -> Generated {
    let mut generated = Generated::default();
    generated
        .source
        .push_str("# Generated by Rusnix. Edit the Rust source.\n");
    emit(ast, &mut generated, 0, &[], options);
    generated.source.push('\n');
    generated
}

fn indent(out: &mut Generated, depth: usize) {
    out.source.push_str(&"  ".repeat(depth));
}

fn emit(
    expr: &NixExpr,
    out: &mut Generated,
    depth: usize,
    enclosing: &[Origin],
    options: RenderOptions,
) {
    if let Some(origin) = &expr.origin {
        if options.origin_comments {
            // Inspection comments carry only our ID, never user-provided text.
            out.source.push_str(&format!("# {}\n", origin.id));
            indent(out, depth);
        }

        let start = out.source.len();
        let mut children_enclosing = enclosing.to_vec();
        children_enclosing.push(origin.clone());
        if expr.error_context {
            out.source.push_str("(builtins.addErrorContext ");
            out.source.push_str(&quote(&origin.id));
            out.source.push_str(" (");
        }

        emit_kind(&expr.kind, out, depth, &children_enclosing, options);
        if expr.error_context {
            out.source.push_str("))");
        }

        let end = out.source.len();
        out.spans.push(SourceSpan {
            start,
            end,
            origin: origin.clone(),
            enclosing: enclosing.to_vec(),
            diagnostic_site: !expr.error_context
                && matches!(
                    expr.kind,
                    NixKind::Call(..)
                        | NixKind::Apply(..)
                        | NixKind::Binary(..)
                        | NixKind::If(..)
                        | NixKind::Select(..)
                        | NixKind::ArgumentSelect(..)
                ),
        });
    } else {
        emit_kind(&expr.kind, out, depth, enclosing, options);
    }
}

fn emit_kind(
    kind: &NixKind,
    out: &mut Generated,
    depth: usize,
    enclosing: &[Origin],
    options: RenderOptions,
) {
    match kind {
        NixKind::Bool(v) => out.source.push_str(if *v { "true" } else { "false" }),
        NixKind::Int(i64::MIN) => out.source.push_str("(-9223372036854775807 - 1)"),
        NixKind::Int(v) if *v < 0 => out.source.push_str(&format!("({v})")),
        NixKind::Int(v) => out.source.push_str(&v.to_string()),
        NixKind::Float(v) => {
            // Keep a decimal point so integral floats remain floats in Nix.
            // Rust's shortest round-trip representation avoids decimal rounding.
            let mut literal = format!("{v:?}");
            if let Some(exponent) = literal.find('e')
                && !literal[..exponent].contains('.')
            {
                literal.insert_str(exponent, ".0");
            }
            out.source.push_str(&format!("({literal})"));
        }
        NixKind::Null => out.source.push_str("null"),
        NixKind::String(v) => out.source.push_str(&quote(v)),
        NixKind::Path(v) => out.source.push_str(v),
        NixKind::Variable(v) => out.source.push_str(v),
        NixKind::Select(value, path) => {
            out.source.push('(');
            emit(value, out, depth, enclosing, options);
            out.source.push(')');
            for part in path {
                out.source.push('.');
                out.source.push_str(&quote(part));
            }
        }
        NixKind::ArgumentSelect(value, path) => {
            if path.is_empty() {
                emit(value, out, depth, enclosing, options);
            } else {
                out.source.push('(');
                emit(value, out, depth, enclosing, options);
                out.source.push(')');
                for part in path {
                    out.source.push('.');
                    if attribute_identifier(part) {
                        out.source.push_str(part);
                    } else {
                        out.source.push_str(&quote(part));
                    }
                }
            }
        }
        NixKind::Lambda(argument, body) => {
            out.source.push_str(&format!("({argument}: "));
            emit(body, out, depth, enclosing, options);
            out.source.push(')');
        }
        NixKind::Function(arguments, body) => {
            out.source.push_str("({ ");
            out.source.push_str(&arguments.join(", "));
            out.source.push_str(", ... }: ");
            emit(body, out, depth, enclosing, options);
            out.source.push(')');
        }
        NixKind::ArgumentFunction(arguments, body) => {
            out.source.push_str("({ ");
            for (index, (name, default)) in arguments.iter().enumerate() {
                if index > 0 {
                    out.source.push_str(", ");
                }
                out.source.push_str(name);
                if let Some(value) = default {
                    out.source.push_str(" ? (");
                    emit(value, out, depth, enclosing, options);
                    out.source.push(')');
                }
            }
            out.source.push_str(" }: ");
            emit(body, out, depth, enclosing, options);
            out.source.push(')');
        }
        NixKind::Group(value) => {
            out.source.push('(');
            emit(value, out, depth, enclosing, options);
            out.source.push(')');
        }
        NixKind::List(items) => {
            out.source.push_str("[ ");
            for item in items {
                emit(item, out, depth, enclosing, options);
                out.source.push(' ');
            }
            out.source.push(']');
        }
        NixKind::AttrSet(bindings) => {
            out.source.push_str("{\n");
            for (path, value) in bindings {
                indent(out, depth + 1);
                out.source
                    .push_str(&path.iter().map(|p| quote(p)).collect::<Vec<_>>().join("."));
                out.source.push_str(" = ");
                emit(value, out, depth + 1, enclosing, options);
                out.source.push_str(";\n");
            }
            indent(out, depth);
            out.source.push('}');
        }
        NixKind::Call(builtin, args) => {
            out.source.push_str(match builtin {
                Builtin::Div => "(builtins.div",
                Builtin::Throw => "(builtins.throw",
                Builtin::Import => "(builtins.import",
                Builtin::GetAttr => "(builtins.getAttr",
                Builtin::ToPath => "(builtins.toPath",
                Builtin::ToString => "(builtins.toString",
            });
            for arg in args {
                out.source.push_str(" (");
                emit(arg, out, depth, enclosing, options);
                out.source.push(')');
            }
            out.source.push(')');
        }
        NixKind::Binary(op, left, right) => {
            out.source.push('(');
            emit(left, out, depth, enclosing, options);
            out.source.push_str(match op {
                BinaryOp::Equal => " == ",
                BinaryOp::GreaterEqual => " >= ",
                BinaryOp::LessEqual => " <= ",
                BinaryOp::And => " && ",
                BinaryOp::Add => " + ",
            });
            emit(right, out, depth, enclosing, options);
            out.source.push(')');
        }
        NixKind::If(condition, yes, no) => {
            out.source.push_str("(if ");
            emit(condition, out, depth, enclosing, options);
            out.source.push_str(" then ");
            emit(yes, out, depth, enclosing, options);
            out.source.push_str(" else ");
            emit(no, out, depth, enclosing, options);
            out.source.push(')');
        }
        NixKind::Let(name, value, body) => {
            out.source.push_str(&format!("(let {name} = "));
            emit(value, out, depth, enclosing, options);
            out.source.push_str("; in ");
            emit(body, out, depth, enclosing, options);
            out.source.push(')');
        }
        NixKind::Apply(function, argument) => {
            out.source.push_str("((");
            emit(function, out, depth, enclosing, options);
            out.source.push_str(") (");
            emit(argument, out, depth, enclosing, options);
            out.source.push_str("))");
        }
    }
}

/// Quoting is required for literal punctuation, interpolation and reserved words.
fn attribute_identifier(name: &str) -> bool {
    let mut chars = name.chars();
    chars
        .next()
        .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
        && chars.all(|c| c.is_ascii_alphanumeric() || "_-'".contains(c))
        && ![
            "if", "then", "else", "assert", "with", "let", "in", "rec", "inherit", "or",
        ]
        .contains(&name)
}

/// Nix string literals, including escaping interpolation; JSON escaping alone
/// would wrongly leave `${...}` executable and use unsupported `\u` escapes.
pub(crate) fn quote(value: &str) -> String {
    let mut out = String::from("\"");
    let mut chars = value.chars().peekable();

    while let Some(c) = chars.next() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
            _ => out.push(c),
        }
    }

    out.push('"');
    out
}
