use crate::ast::{BinaryOp, Builtin, NixExpr, NixKind};
use rusnix_ir::Origin;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct SourceSpan {
    pub start: usize,
    pub end: usize,
    pub origin: Origin,
    /// Static semantic ancestry, independent of which Nix contexts remain active.
    #[serde(default)]
    pub enclosing: Vec<Origin>,
}

#[derive(Clone, Debug, Default, Serialize, Deserialize)]
pub struct Generated {
    pub source: String,
    pub spans: Vec<SourceSpan>,
}

impl Generated {
    pub fn origin(&self, id: &str) -> Option<&Origin> {
        self.spans
            .iter()
            .find(|span| span.origin.id == id)
            .map(|span| &span.origin)
    }

    pub fn at_position(&self, line: usize, column: usize) -> Option<&Origin> {
        self.span_at_position(line, column).map(|span| &span.origin)
    }

    pub fn span_at_position(&self, line: usize, column: usize) -> Option<&SourceSpan> {
        if line == 0 || column == 0 {
            return None;
        }
        let start = if line == 1 {
            0
        } else {
            self.source.match_indices('\n').nth(line - 2)?.0 + 1
        };
        let line_end = self.source[start..]
            .find('\n')
            .map_or(self.source.len(), |n| start + n);
        let offset = start.checked_add(column - 1)?;
        if offset >= line_end {
            return None;
        }
        self.spans
            .iter()
            .filter(|span| span.start <= offset && offset < span.end)
            .min_by_key(|span| span.end - span.start)
    }
}

pub fn render(ast: &NixExpr) -> Generated {
    let mut generated = Generated::default();
    generated
        .source
        .push_str("# Generated by Rusnix. Edit the Rust source.\n");
    emit(ast, &mut generated, 0, &[]);
    generated.source.push('\n');
    generated
}

fn indent(out: &mut Generated, depth: usize) {
    out.source.push_str(&"  ".repeat(depth));
}

fn emit(expr: &NixExpr, out: &mut Generated, depth: usize, enclosing: &[Origin]) {
    if let Some(origin) = &expr.origin {
        // Comments carry only our ID, never unescaped user-provided text.
        out.source
            .push_str(&format!("# rusnix-origin:{}\n", origin.id));
        indent(out, depth);
        let start = out.source.len();
        let mut children_enclosing = enclosing.to_vec();
        children_enclosing.push(origin.clone());
        if expr.error_context {
            out.source.push_str("(builtins.addErrorContext ");
            out.source
                .push_str(&quote(&format!("rusnix-origin:{}", origin.id)));
            out.source.push_str(" (");
        }
        emit_kind(&expr.kind, out, depth, &children_enclosing);
        if expr.error_context {
            out.source.push_str("))");
        }
        let end = out.source.len();
        out.spans.push(SourceSpan {
            start,
            end,
            origin: origin.clone(),
            enclosing: enclosing.to_vec(),
        });
    } else {
        emit_kind(&expr.kind, out, depth, enclosing);
    }
}

fn emit_kind(kind: &NixKind, out: &mut Generated, depth: usize, enclosing: &[Origin]) {
    match kind {
        NixKind::Bool(v) => out.source.push_str(if *v { "true" } else { "false" }),
        NixKind::Int(i64::MIN) => out.source.push_str("(-9223372036854775807 - 1)"),
        NixKind::Int(v) if *v < 0 => out.source.push_str(&format!("({v})")),
        NixKind::Int(v) => out.source.push_str(&v.to_string()),
        NixKind::Float(v) => {
            // Keep a decimal point so integral floats remain floats in Nix.
            // Rust's shortest round-trip representation avoids decimal rounding.
            let mut literal = format!("{v:?}");
            if let Some(exponent) = literal.find('e')
                && !literal[..exponent].contains('.')
            {
                literal.insert_str(exponent, ".0");
            }
            out.source.push_str(&format!("({literal})"));
        }
        NixKind::Null => out.source.push_str("null"),
        NixKind::String(v) => out.source.push_str(&quote(v)),
        NixKind::Path(v) => out.source.push_str(v),
        NixKind::Variable(v) => out.source.push_str(v),
        NixKind::Select(value, path) => {
            out.source.push('(');
            emit(value, out, depth, enclosing);
            out.source.push(')');
            for part in path {
                out.source.push('.');
                out.source.push_str(&quote(part));
            }
        }
        NixKind::Function(arguments, body) => {
            out.source.push_str("({ ");
            out.source.push_str(&arguments.join(", "));
            out.source.push_str(", ... }: ");
            emit(body, out, depth, enclosing);
            out.source.push(')');
        }
        NixKind::Group(value) => {
            out.source.push('(');
            emit(value, out, depth, enclosing);
            out.source.push(')');
        }
        NixKind::List(items) => {
            out.source.push_str("[ ");
            for item in items {
                emit(item, out, depth, enclosing);
                out.source.push(' ');
            }
            out.source.push(']');
        }
        NixKind::AttrSet(bindings) => {
            out.source.push_str("{\n");
            for (path, value) in bindings {
                indent(out, depth + 1);
                out.source
                    .push_str(&path.iter().map(|p| quote(p)).collect::<Vec<_>>().join("."));
                out.source.push_str(" = ");
                emit(value, out, depth + 1, enclosing);
                out.source.push_str(";\n");
            }
            indent(out, depth);
            out.source.push('}');
        }
        NixKind::Call(builtin, args) => {
            out.source.push_str(match builtin {
                Builtin::Div => "(builtins.div",
                Builtin::Throw => "(builtins.throw",
                Builtin::Import => "(builtins.import",
                Builtin::GetAttr => "(builtins.getAttr",
                Builtin::ToPath => "(builtins.toPath",
                Builtin::ToString => "(builtins.toString",
            });
            for arg in args {
                out.source.push_str(" (");
                emit(arg, out, depth, enclosing);
                out.source.push(')');
            }
            out.source.push(')');
        }
        NixKind::Binary(op, left, right) => {
            out.source.push('(');
            emit(left, out, depth, enclosing);
            out.source.push_str(match op {
                BinaryOp::GreaterEqual => " >= ",
                BinaryOp::LessEqual => " <= ",
                BinaryOp::And => " && ",
                BinaryOp::Add => " + ",
            });
            emit(right, out, depth, enclosing);
            out.source.push(')');
        }
        NixKind::If(condition, yes, no) => {
            out.source.push_str("(if ");
            emit(condition, out, depth, enclosing);
            out.source.push_str(" then ");
            emit(yes, out, depth, enclosing);
            out.source.push_str(" else ");
            emit(no, out, depth, enclosing);
            out.source.push(')');
        }
        NixKind::Let(name, value, body) => {
            out.source.push_str(&format!("(let {name} = "));
            emit(value, out, depth, enclosing);
            out.source.push_str("; in ");
            emit(body, out, depth, enclosing);
            out.source.push(')');
        }
        NixKind::Apply(function, argument) => {
            out.source.push_str("((");
            emit(function, out, depth, enclosing);
            out.source.push_str(") (");
            emit(argument, out, depth, enclosing);
            out.source.push_str("))");
        }
    }
}

/// Nix string literals, including escaping interpolation; JSON escaping alone
/// would wrongly leave `${...}` executable and use unsupported `\u` escapes.
pub fn quote(value: &str) -> String {
    let mut out = String::from("\"");
    let mut chars = value.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            '$' if chars.peek() == Some(&'{') => out.push_str("\\$"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}
