//! Author NixOS declarations while delegating validation and merging to lib.types.
use crate::{
    IntoRusnixValue, RusnixValue, ValidationError,
    interop::{NixValue, Nixpkgs},
};

/// An opaque NixOS option type, distinct from a Rust field's static type.
/// This wraps real lib.types values; NixOS owns their checks, coercions and merges.
#[derive(Clone, Debug)]
pub struct OptionType(NixValue);

impl OptionType {
    /// Select a real named lib.types value, such as bool, str, path, port or package.
    /// Names are checked by Nix rather than a generated Rust catalogue.
    #[track_caller]
    pub fn named(name: &str) -> Self {
        Self(Nixpkgs::new().lib_value(&format!("types.{name}")))
    }

    /// Wrap a custom or composed type supplied by existing Nix code.
    pub fn opaque(value: NixValue) -> Self {
        Self(value)
    }

    /// Access the real Nix-side type without evaluating it in Rust.
    pub fn as_value(&self) -> NixValue {
        self.0.clone()
    }

    /// Allow Nix null in addition to this type's values.
    #[track_caller]
    pub fn null_or(self) -> Self {
        Self(Nixpkgs::new().function("types.nullOr").call(self.0))
    }

    /// Use NixOS's ordered list-of-elements merge semantics.
    #[track_caller]
    pub fn list_of(self) -> Self {
        Self(Nixpkgs::new().function("types.listOf").call(self.0))
    }

    /// Merge arbitrary literal attribute keys with this type for each value.
    #[track_caller]
    pub fn attrs_of(self) -> Self {
        Self(Nixpkgs::new().function("types.attrsOf").call(self.0))
    }

    /// Declare a deferred function returning values of this type.
    #[track_caller]
    pub fn function_to(self) -> Self {
        Self(Nixpkgs::new().function("types.functionTo").call(self.0))
    }

    /// Accept one of the supplied NixOS types using upstream selection and merging.
    #[track_caller]
    pub fn one_of(types: impl IntoIterator<Item = Self>) -> Self {
        Self(
            Nixpkgs::new()
                .function("types.oneOf")
                .call(NixValue::list(types.into_iter().map(|t| t.0))),
        )
    }

    /// Coerce values of another type with a deferred Nix function before merging.
    #[track_caller]
    pub fn coerced_from(self, source: Self, coercion: NixValue) -> Self {
        Self(
            Nixpkgs::new()
                .function("types.coercedTo")
                .apply([source.0, coercion, self.0]),
        )
    }

    /// Declare nested options using ordinary structural lowering; an optional
    /// freeform type keeps undeclared keys open with NixOS's actual validation.
    /// Shape errors are reported in Rust; submodule checks and defaults stay in Nix.
    #[track_caller]
    pub fn submodule(
        options: impl IntoRusnixValue,
        freeform: Option<Self>,
    ) -> Result<Self, ValidationError> {
        let mut fields = vec![("options", options.into_value().into_nix_value()?)];
        if let Some(ty) = freeform {
            fields.push(("freeformType", ty.0));
        }

        Ok(Self(
            Nixpkgs::new()
                .function("types.submodule")
                .call(NixValue::record(fields)),
        ))
    }
}

/// One public NixOS option declaration, used as a leaf of a structural schema.
/// Metadata stays explicit. This declares the backend interface; it neither
/// replaces Rust types nor provides a concrete option value in Rust.
#[derive(Clone, Debug)]
pub struct OptionDecl {
    value: NixValue,
}

impl OptionDecl {
    /// Start a declaration with a real NixOS type and no default.
    #[track_caller]
    pub fn new(ty: OptionType) -> Self {
        Self::from_value(
            Nixpkgs::new()
                .function("mkOption")
                .call(NixValue::record([("type", ty.0)])),
        )
    }

    /// Preserve an option generated by an existing Nix declaration helper.
    pub fn from_value(value: NixValue) -> Self {
        Self { value }
    }

    /// Use mkEnableOption, retaining its standard default, example and description.
    #[track_caller]
    pub fn enable(description: &str) -> Self {
        Self::from_value(Nixpkgs::new().function("mkEnableOption").call(description))
    }

    #[track_caller]
    fn metadata(mut self, name: &str, value: NixValue) -> Self {
        self.value = Nixpkgs::new()
            .function("mergeAttrs")
            .apply([self.value, NixValue::record([(name, value)])]);
        self
    }

    /// Supply an actual option default, which remains lazy and may be symbolic.
    #[track_caller]
    pub fn default(self, value: impl Into<NixValue>) -> Self {
        self.metadata("default", value.into())
    }

    /// Supply documentation for a default without defining an actual value.
    #[track_caller]
    pub fn default_text(self, value: impl Into<NixValue>) -> Self {
        self.metadata("defaultText", value.into())
    }

    /// Attach an upstream-compatible example, including literalExpression values.
    #[track_caller]
    pub fn example(self, value: impl Into<NixValue>) -> Self {
        self.metadata("example", value.into())
    }

    /// Describe the public option using NixOS's markdown documentation conventions.
    #[track_caller]
    pub fn description(self, value: impl Into<NixValue>) -> Self {
        self.metadata("description", value.into())
    }

    /// Mark this option as internal to the module interface.
    #[track_caller]
    pub fn internal(self) -> Self {
        self.metadata("internal", true.into())
    }

    /// Let NixOS reject multiple definitions of this read-only option.
    #[track_caller]
    pub fn read_only(self) -> Self {
        self.metadata("readOnly", true.into())
    }
}

impl IntoRusnixValue for OptionDecl {
    #[track_caller]
    fn into_value(self) -> RusnixValue {
        self.value.into_value()
    }
}
