[package]
name = "rusix-nix"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
rusix-ir.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
sha2.workspace = true

[[example]]
name = "enum-option"
path = "../../examples/enum-option.rs"

[[example]]
name = "typed-submodule"
path = "../../examples/typed-submodule.rs"

[[example]]
name = "invalid-states"
path = "../../examples/invalid-states.rs"

[[example]]
name = "function-contracts"
path = "../../examples/function-contracts.rs"

[[example]]
name = "exhaustive-match"
path = "../../examples/exhaustive-match.rs"

[[example]]
name = "typed-values"
path = "../../examples/typed-values.rs"

[[example]]
name = "layered-validation"
path = "../../examples/layered-validation.rs"

[[example]]
name = "nix-interop"
path = "../../examples/nix-interop.rs"

[[example]]
name = "symbolic-option"
path = "../../examples/symbolic-option.rs"

[[example]]
name = "postgresql-nixos-module"
path = "../../examples/postgresql-nixos-module/main.rs"

[[example]]
name = "git-nixpkg"
path = "../../examples/git-nixpkg/main.rs"

[[example]]
name = "curl-nixpkg"
path = "../../examples/curl-nixpkg/main.rs"

[[example]]
name = "openssl-nixpkg"
path = "../../examples/openssl-nixpkg/main.rs"

[[example]]
name = "composed-packages"
path = "../../examples/composed-packages/main.rs"

[[example]]
name = "mariadb-nixpkg"
path = "../../examples/mariadb-nixpkg/main.rs"

[[example]]
name = "overlay"
path = "../../examples/overlay/main.rs"
