//! Reproduces curlMinimal's complete pinned package recipe with real nixpkgs builders.
use super::inputs::{ARGUMENTS, Inputs, args};
use rusnix_ir::{
    IntoRusnixValue,
    interop::{NixLibrary, NixValue, PackageFunction},
    nix_text,
};

/// Describe the ordinary Nix package function, including dependent lazy defaults.
pub(super) fn factory() -> PackageFunction {
    PackageFunction::from_function_attrs(ARGUMENTS.iter().copied(), |arguments| {
        let i = args::from_value(arguments);
        let host = &i.stdenv.host_platform;
        let defaults = vec![
            ("brotliSupport", false.into()),
            ("c-aresSupport", false.into()),
            ("gnutlsSupport", false.into()),
            ("gsaslSupport", false.into()),
            (
                "gssSupport",
                (!host.is_windows())
                    .and(!host.is_static())
                    .and(!host.is_darwin().and((!i.native()).into_expr()))
                    .into(),
            ),
            ("http2Support", true.into()),
            ("http3Support", false.into()),
            ("websocketSupport", false.into()),
            ("idnSupport", false.into()),
            ("ldapSupport", false.into()),
            ("opensslSupport", i.zlib_support().into()),
            ("pslSupport", false.into()),
            ("rtmpSupport", false.into()),
            (
                "scpSupport",
                i.zlib_support()
                    .and(!host.is_sun_os())
                    .and(!host.is_cygwin())
                    .into(),
            ),
            ("wolfsslSupport", false.into()),
            ("rustlsSupport", false.into()),
            ("zlibSupport", true.into()),
            ("zstdSupport", false.into()),
        ];

        // The public interface remains four independent booleans. Count with the
        // caller's lib, then use Nix's native assertion, as the pinned source does.
        let count = i.lib.as_value().select("count").apply([
            NixValue::function(|value| value),
            NixValue::list([
                i.gnutls_support().into(),
                i.openssl_support().into(),
                i.wolfssl_support().into(),
                i.rustls_support().into(),
            ]),
        ]);
        let valid = !NixValue::builtin("lessThan").apply([1_i64.into(), count]);
        let derivation = i
            .stdenv
            .mk_derivation()
            .call(NixValue::function(|final_attrs| {
                attributes(&i, final_attrs)
            }));

        (defaults, NixValue::assert(valid, derivation))
    })
}

/// Curl's fixed recipe fields; nixpkgs still owns their build and override semantics.
#[derive(IntoRusnixValue)]
struct Derivation {
    /// Stable package name, independent of the selected protocol features.
    pname: &'static str,
    /// Pinned release; finalAttrs references observe later version overrides.
    version: &'static str,
    /// Fixed-output source recipe, constructed without fetching its output.
    src: NixValue,
    /// Applies the bootstrap-safe local configure/script substitutions.
    post_patch: NixValue,
    /// Ordered program, header, library and documentation outputs.
    outputs: Vec<&'static str>,
    /// Linux enables stdenv's separate debug output.
    separate_debug_info: NixValue,
    /// Allows the real builder to run independent make jobs concurrently.
    enable_parallel_building: bool,
    /// Keeps build-tool and target dependency roles distinct in stdenv.
    strict_deps: bool,
    /// Static Darwin linker workaround, omitted otherwise through lib.optionalAttrs.
    env: NixValue,
    /// pkg-config and Perl are build-platform tools supplied by callPackage.
    native_build_inputs: NixValue,
    /// Feature-selected libraries propagated to libcurl consumers, in upstream order.
    propagated_build_inputs: NixValue,
    /// Prevents host-path detection and applies the optional static PSL workaround.
    pre_configure: NixValue,
    /// Configure switches generated by the caller's feature and output helpers.
    configure_flags: NixValue,
    /// Target C++ compiler command, including the caller's cross prefix.
    #[rusnix(rename = "CXX")]
    cxx: NixValue,
    /// Target C++ preprocessing command used by configure.
    #[rusnix(rename = "CXXCPP")]
    cxxcpp: NixValue,
    /// The regular package skips the expensive suite; passthru.withCheck enables it.
    do_check: bool,
    /// Patches test interpreters and removes platform-specific failing tests.
    pre_check: NixValue,
    /// Splits curl-config, installs completions and applies backend-specific fixes.
    post_install: NixValue,
    /// Recursive package consumers and checks that use finalAttrs.finalPackage.
    passthru: NixValue,
    /// Public package documentation and platform/feature availability metadata.
    meta: Metadata,
}

/// The pinned metadata remains a local record, not a universal nixpkgs schema.
#[derive(IntoRusnixValue)]
struct Metadata {
    /// Release-specific changelog URL, following a final version override.
    changelog: NixValue,
    /// Upstream summary used by package search and documentation.
    description: &'static str,
    /// curl project's homepage.
    homepage: &'static str,
    /// Existing curl license metadata from the caller's library.
    license: NixValue,
    /// Existing upstream maintainer record, retained as a Nix value.
    maintainers: NixValue,
    /// Supported platform list from nixpkgs.
    platforms: NixValue,
    /// Static brotli or GSS builds are declared broken, exactly as upstream.
    broken: NixValue,
    /// Expected pkg-config module, consumed by the passthru metadata check.
    pkg_config_modules: Vec<&'static str>,
    /// Executable selected by ordinary package runners.
    main_program: &'static str,
}

/// Construct recipe attributes inside mkDerivation's recursive finalAttrs callback.
fn attributes(i: &Inputs, final_attrs: NixValue) -> NixValue {
    let lib = NixLibrary::from_value(i.lib.as_value());
    let version = final_attrs.clone().select("version");
    let release_tag = NixValue::builtin("replaceStrings").apply([
        NixValue::list([".".into()]),
        NixValue::list(["_".into()]),
        version.clone(),
    ]);

    // curl bootstraps fetchurl. Source/patch handling must not introduce fetchpatch;
    // that argument is used only by the existing lazy passthru test graph.
    let source = i.fetchurl().call(NixValue::record([
        (
            "urls",
            NixValue::list([
                nix_text!(
                    "https://curl.haxx.se/download/curl-{version}.tar.xz",
                    version = version.clone(),
                ),
                nix_text!(
                    "https://github.com/curl/curl/releases/download/curl-{tag}/curl-{version}.tar.xz",
                    tag = release_tag,
                    version = version.clone(),
                ),
            ]),
        ),
        ("hash", "sha256-21nPDWccpuf1wsXsF3CEozp54EyX5xzxg6XN6iNQVOs=".into()),
    ]));

    Derivation {
        pname: "curl",
        version: "8.11.0",
        src: source,
        post_patch: nix_text!(
            r#"
                substituteInPlace ./config.guess --replace-fail /usr/bin/uname uname
                patchShebangs scripts
            "#,
        ),
        outputs: vec!["bin", "dev", "out", "man", "devdoc"],
        separate_debug_info: i.stdenv.host_platform.is_linux().into(),
        enable_parallel_building: true,
        strict_deps: true,
        env: lib.as_value().clone().select("optionalAttrs").apply([
            i.stdenv
                .host_platform
                .is_darwin()
                .and(i.stdenv.host_platform.is_static())
                .into(),
            NixValue::record([("NIX_LDFLAGS", "-liconv".into())]),
        ]),
        native_build_inputs: NixValue::list([i.pkg_config(), i.perl()]),
        propagated_build_inputs: dependencies(i, &lib),
        pre_configure: NixValue::concat_text([
            nix_text!(
                r#"
                    sed -e 's|/usr/bin|/no-such-path|g' -i.bak configure
                    rm src/tool_hugehelp.c
                "#,
            ),
            lib.optional_text(
                i.psl_support().and(i.stdenv.host_platform.is_static()),
                nix_text!(
                    r#"
                        # curl doesn't understand that libpsl2 has deps because it doesn't use
                        # pkg-config.
                        # https://github.com/curl/curl/pull/12919
                        configureFlagsArray+=("LIBS=-lidn2 -lunistring")
                    "#,
                ),
            ),
        ]),
        configure_flags: configure_flags(i, &lib),
        cxx: nix_text!("{prefix}c++", prefix = i.stdenv.cc.target_prefix()),
        cxxcpp: nix_text!("{prefix}c++ -E", prefix = i.stdenv.cc.target_prefix()),
        do_check: false,
        pre_check: pre_check(i, &lib),
        post_install: post_install(i, &lib),
        passthru: passthru(i, final_attrs),
        meta: Metadata {
            changelog: nix_text!("https://curl.se/ch/{version}.html", version = version),
            description: "Command line tool for transferring files with URL syntax",
            homepage: "https://curl.se/",
            license: i.lib.licenses.curl(),
            maintainers: NixValue::list([i.lib.maintainers.lovek323()]),
            platforms: i.lib.platforms.all(),
            broken: i
                .stdenv
                .host_platform
                .is_static()
                .and(!(!i.brotli_support()).and(!i.gss_support()))
                .into(),
            pkg_config_modules: vec!["libcurl"],
            main_program: "curl",
        },
    }
    .try_into_nix_value()
    .expect("curl's fixed records have no structural flattening")
}

/// Preserve upstream's dependency sequence; excluded optional packages remain lazy.
/// Native concatenation must not consult an overridden lib.concatLists: upstream uses ++.
fn dependencies(i: &Inputs, lib: &NixLibrary) -> NixValue {
    NixValue::builtin("concatLists").call(NixValue::list([
        lib.optional(i.brotli_support(), i.brotli()),
        lib.optional(i.c_ares_support(), i.c_ares_minimal()),
        lib.optional(i.gnutls_support(), i.gnutls()),
        lib.optional(i.gsasl_support(), i.gsasl()),
        lib.optional(i.gss_support(), i.libkrb5()),
        lib.optional(i.http2_support(), i.nghttp2()),
        lib.optionals(i.http3_support(), NixValue::list([i.nghttp3(), i.ngtcp2()])),
        lib.optional(i.idn_support(), i.libidn2()),
        lib.optional(i.ldap_support(), i.openldap()),
        lib.optional(i.openssl_support(), i.openssl()),
        lib.optional(i.psl_support(), i.libpsl()),
        lib.optional(i.rtmp_support(), i.rtmpdump()),
        lib.optional(i.scp_support(), i.libssh2()),
        lib.optional(i.wolfssl_support(), i.wolfssl()),
        lib.optional(i.rustls_support(), i.rustls_ffi()),
        lib.optional(i.zlib_support(), i.zlib()),
        lib.optional(i.zstd_support(), i.zstd()),
        lib.optionals(
            i.stdenv.host_platform.is_darwin(),
            NixValue::list([
                i.darwin.apple_sdk.frameworks.core_foundation(),
                i.darwin.apple_sdk.frameworks.core_services(),
                i.darwin.apple_sdk.frameworks.system_configuration(),
            ]),
        ),
    ]))
}

/// Call the supplied library's configure helpers; disabled output arguments stay deferred.
fn configure_flags(i: &Inputs, lib: &NixLibrary) -> NixValue {
    let raw = lib.as_value();
    let mut flags = vec![
        "--enable-versioned-symbols".into(),
        "--disable-manual".into(),
    ];

    for (condition, name) in [
        (i.c_ares_support(), "ares"),
        (i.ldap_support(), "ldap"),
        (i.ldap_support(), "ldaps"),
        (i.websocket_support(), "websockets"),
    ] {
        flags.push(
            raw.clone()
                .select("enableFeature")
                .apply([condition.into(), name.into()]),
        );
    }

    for (condition, name) in [
        (
            (!(!i.openssl_support()).and(!i.gnutls_support())),
            "ca-fallback",
        ),
        (i.http3_support(), "nghttp3"),
        (i.http3_support(), "ngtcp2"),
        (i.rtmp_support(), "librtmp"),
        (i.rustls_support(), "rustls"),
        (i.zstd_support(), "zstd"),
        (i.psl_support(), "libpsl"),
    ] {
        flags.push(
            raw.clone()
                .select("withFeature")
                .apply([condition.into(), name.into()]),
        );
    }

    for (condition, name, package) in [
        (i.brotli_support(), "brotli", i.brotli()),
        (i.gnutls_support(), "gnutls", i.gnutls()),
        (i.idn_support(), "libidn2", i.libidn2()),
        (i.openssl_support(), "openssl", i.openssl()),
        (i.scp_support(), "libssh2", i.libssh2()),
        (i.wolfssl_support(), "wolfssl", i.wolfssl()),
    ] {
        let output = raw.clone().select("getDev").call(package);
        flags.push(raw.clone().select("withFeatureAs").apply([
            condition.into(),
            name.into(),
            output,
        ]));
    }

    NixValue::builtin("concatLists").call(NixValue::list([
        NixValue::list(flags),
        lib.optional(
            i.gss_support(),
            nix_text!(
                "--with-gssapi={krb5}",
                krb5 = raw.clone().select("getDev").call(i.libkrb5()),
            ),
        ),
        lib.optional(!i.native(), "--with-random=/dev/urandom"),
        lib.optionals(
            i.stdenv.host_platform.is_darwin(),
            NixValue::list(["--without-ca-bundle".into(), "--without-ca-path".into()]),
        ),
        lib.optionals(
            (!i.gnutls_support())
                .and(!i.openssl_support())
                .and(!i.wolfssl_support())
                .and(!i.rustls_support()),
            NixValue::list(["--without-ssl".into()]),
        ),
        lib.optionals(
            i.rustls_support().and(!i.stdenv.host_platform.is_darwin()),
            NixValue::list(["--with-ca-bundle=/etc/ssl/certs/ca-certificates.crt".into()]),
        ),
        lib.optionals(
            i.gnutls_support().and(!i.stdenv.host_platform.is_darwin()),
            NixValue::list(["--with-ca-path=/etc/ssl/certs".into()]),
        ),
    ]))
}

/// Prepare checks without running them during expression evaluation.
fn pre_check(i: &Inputs, lib: &NixLibrary) -> NixValue {
    NixValue::concat_text([
        nix_text!(
            r#"
                patchShebangs tests/
            "#,
        ),
        lib.optional_text(
            i.stdenv.host_platform.is_darwin(),
            nix_text!(
                r#"
                # bad interaction with sandbox if enabled?
                rm tests/data/test1453
                rm tests/data/test1086
            "#,
            ),
        ),
        lib.optional_text(
            i.stdenv.host_platform.is_musl(),
            nix_text!(
                r#"
                # different resolving behaviour?
                rm tests/data/test1592
            "#,
            ),
        ),
    ])
}

/// Retain exact shell bytes and store-path dependency contexts in backend-specific fixes.
fn post_install(i: &Inputs, lib: &NixLibrary) -> NixValue {
    NixValue::concat_text([
        nix_text!(
            r#"
                moveToOutput bin/curl-config "$dev"

                # Install completions
                make -C scripts install
            "#,
        ),
        lib.optional_text(
            i.scp_support(),
            nix_text!(
                r#"
                sed '/^dependency_libs/s|{dev}|{lib}|' -i "$out"/lib/*.la
            "#,
                dev = lib.as_value().clone().select("getDev").call(i.libssh2()),
                lib = lib.as_value().clone().select("getLib").call(i.libssh2()),
            ),
        ),
        lib.optional_text(
            i.gnutls_support(),
            nix_text!(
                r#"
                ln $out/lib/libcurl{ext} $out/lib/libcurl-gnutls{ext}
                ln $out/lib/libcurl{ext} $out/lib/libcurl-gnutls{ext}.4
                ln $out/lib/libcurl{ext} $out/lib/libcurl-gnutls{ext}.4.4.0
            "#,
                ext = i.stdenv.host_platform.extensions.shared_library(),
            ),
        ),
    ])
}

/// Override a consuming package with the eventual curl, not an earlier recipe snapshot.
#[track_caller]
fn use_this_curl(package: NixValue, curl: &NixValue) -> NixValue {
    package
        .select("override")
        .call(NixValue::record([("curl", curl.clone())]))
}

/// Preserve the recursive test graph; requesting these values constructs recipes only.
fn passthru(i: &Inputs, final_attrs: NixValue) -> NixValue {
    let curl = final_attrs.select("finalPackage");
    let with_check = curl
        .clone()
        .select("overrideAttrs")
        .call(NixValue::function(|_| {
            NixValue::record([("doCheck", true.into())])
        }));
    let fetchpatch = i
        .fetchpatch()
        .select("override")
        .call(NixValue::record([(
            "fetchurl",
            use_this_curl(i.fetchurl(), &curl),
        )]))
        .merge_attrs(NixValue::record([("version", 1_i64.into())]));
    let fetchpatch_test = i
        .tests
        .fetchpatch
        .simple()
        .select("override")
        .call(NixValue::record([("fetchpatch", fetchpatch)]));

    NixValue::record([
        ("opensslSupport", i.openssl_support().into()),
        ("openssl", i.openssl()),
        (
            "tests",
            NixValue::record([
                ("withCheck", with_check),
                ("fetchpatch", fetchpatch_test),
                ("curlpp", use_this_curl(i.curlpp(), &curl)),
                ("coeurl", use_this_curl(i.coeurl(), &curl)),
                (
                    "haskell-curl",
                    use_this_curl(i.haskell_packages.curl(), &curl),
                ),
                (
                    "ocaml-curly",
                    use_this_curl(i.ocaml_packages.curly(), &curl),
                ),
                ("pycurl", use_this_curl(i.python3.pkgs.pycurl(), &curl)),
                ("php-curl", use_this_curl(i.php_extensions.curl(), &curl)),
                ("nginx-http3", i.nixos_tests.nginx_http3()),
                ("pkg-config", i.testers.test_meta_pkg_config().call(curl)),
                ("static", i.pkgs_static.curl()),
            ]),
        ),
    ])
}
